/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppLifelineRouteImport } from './routes/_authenticated/app.lifeline'
import { Route as AuthenticatedAppCheckRouteImport } from './routes/_authenticated/app.check'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated/app.alerts'
import { Route as ApiPublicHooksSyncTransactionsRouteImport } from './routes/api/public/hooks/sync-transactions'
import { Route as AuthenticatedAppEldersNewRouteImport } from './routes/_authenticated/app.elders.new'
import { Route as AuthenticatedAppEldersIdRouteImport } from './routes/_authenticated/app.elders.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLifelineRoute =
  AuthenticatedAppLifelineRouteImport.update({
    id: '/lifeline',
    path: '/lifeline',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCheckRoute = AuthenticatedAppCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicHooksSyncTransactionsRoute =
  ApiPublicHooksSyncTransactionsRouteImport.update({
    id: '/api/public/hooks/sync-transactions',
    path: '/api/public/hooks/sync-transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppEldersNewRoute =
  AuthenticatedAppEldersNewRouteImport.update({
    id: '/elders/new',
    path: '/elders/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEldersIdRoute =
  AuthenticatedAppEldersIdRouteImport.update({
    id: '/elders/$id',
    path: '/elders/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/check': typeof AuthenticatedAppCheckRoute
  '/app/lifeline': typeof AuthenticatedAppLifelineRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/elders/$id': typeof AuthenticatedAppEldersIdRoute
  '/app/elders/new': typeof AuthenticatedAppEldersNewRoute
  '/api/public/hooks/sync-transactions': typeof ApiPublicHooksSyncTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/check': typeof AuthenticatedAppCheckRoute
  '/app/lifeline': typeof AuthenticatedAppLifelineRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/elders/$id': typeof AuthenticatedAppEldersIdRoute
  '/app/elders/new': typeof AuthenticatedAppEldersNewRoute
  '/api/public/hooks/sync-transactions': typeof ApiPublicHooksSyncTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/check': typeof AuthenticatedAppCheckRoute
  '/_authenticated/app/lifeline': typeof AuthenticatedAppLifelineRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/elders/$id': typeof AuthenticatedAppEldersIdRoute
  '/_authenticated/app/elders/new': typeof AuthenticatedAppEldersNewRoute
  '/api/public/hooks/sync-transactions': typeof ApiPublicHooksSyncTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/app'
    | '/app/alerts'
    | '/app/check'
    | '/app/lifeline'
    | '/app/'
    | '/app/elders/$id'
    | '/app/elders/new'
    | '/api/public/hooks/sync-transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/app/alerts'
    | '/app/check'
    | '/app/lifeline'
    | '/app'
    | '/app/elders/$id'
    | '/app/elders/new'
    | '/api/public/hooks/sync-transactions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/check'
    | '/_authenticated/app/lifeline'
    | '/_authenticated/app/'
    | '/_authenticated/app/elders/$id'
    | '/_authenticated/app/elders/new'
    | '/api/public/hooks/sync-transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksSyncTransactionsRoute: typeof ApiPublicHooksSyncTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lifeline': {
      id: '/_authenticated/app/lifeline'
      path: '/lifeline'
      fullPath: '/app/lifeline'
      preLoaderRoute: typeof AuthenticatedAppLifelineRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/check': {
      id: '/_authenticated/app/check'
      path: '/check'
      fullPath: '/app/check'
      preLoaderRoute: typeof AuthenticatedAppCheckRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/sync-transactions': {
      id: '/api/public/hooks/sync-transactions'
      path: '/api/public/hooks/sync-transactions'
      fullPath: '/api/public/hooks/sync-transactions'
      preLoaderRoute: typeof ApiPublicHooksSyncTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/elders/new': {
      id: '/_authenticated/app/elders/new'
      path: '/elders/new'
      fullPath: '/app/elders/new'
      preLoaderRoute: typeof AuthenticatedAppEldersNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/elders/$id': {
      id: '/_authenticated/app/elders/$id'
      path: '/elders/$id'
      fullPath: '/app/elders/$id'
      preLoaderRoute: typeof AuthenticatedAppEldersIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppCheckRoute: typeof AuthenticatedAppCheckRoute
  AuthenticatedAppLifelineRoute: typeof AuthenticatedAppLifelineRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppEldersIdRoute: typeof AuthenticatedAppEldersIdRoute
  AuthenticatedAppEldersNewRoute: typeof AuthenticatedAppEldersNewRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppCheckRoute: AuthenticatedAppCheckRoute,
  AuthenticatedAppLifelineRoute: AuthenticatedAppLifelineRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppEldersIdRoute: AuthenticatedAppEldersIdRoute,
  AuthenticatedAppEldersNewRoute: AuthenticatedAppEldersNewRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksSyncTransactionsRoute: ApiPublicHooksSyncTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
